version: "3.9"

services:
  db:
    image: postgres:15
    container_name: telegram-scaping-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_pipeline_app
    env_file:
      - .env
    volumes:
      - .:/app
      - ./.dbt:/app/.dbt
    environment:
      - POSTGRES_HOST=db
      - DBT_PROFILES_DIR=/app/.dbt
    depends_on:
      - db

volumes:
  postgres_data:
